const express = require('express')
const routes = require('./routes')
const cors = require('cors')
require('./database')
const server = express()
server.use(cors())
server.use(express.json())
server.use(routes)
server.listen(3030, () => console.log('Running on 3030'))